Repository Reuven1203/TeamF_SOEN341Project2022, pull requests merged in 2022-02, with the labels that each got.

#36 Add draft for Sprint 2 .txt file
  Sprint 2/Sprint 2.txt
  Sprint 2/sprint2.txt
Labels: documentation

#41 Categories Template
  Frontend/Categories_Laptop.html
  Frontend/img/BetterBuy_logo2.png
  Frontend/img/product/Product1.jpg
  Frontend/img/product/Product10.png
  Frontend/img/product/Product11.png
  Frontend/img/product/Product12.png
  Frontend/img/product/Product2.jfif
  Frontend/img/product/Product3.jfif
  Frontend/img/product/Product4.jpg
  Frontend/img/product/Product5.jpg
  Frontend/img/product/Product6.jpg
  Frontend/img/product/Product7.jpg
  Frontend/img/product/Product8.jpg
  Frontend/img/product/Product9.png
Labels: Task

#43 Update Sprint 2.txt
  Sprint 2/Sprint 2.txt
Labels: documentation

#42 remove unnecessary text from register template
  Frontend/register.html
Labels: Task

#44 Create Sprint 2.docx
  Sprint 2/.DS_Store
  Sprint 2/Sprint 2.docx
  Sprint 2/Sprint 2.txt
Labels: documentation

#45 Phone Category and Category Page
  .DS_Store
  Frontend/.DS_Store
  Frontend/Categories_Phone.html
  Frontend/category.html
  Frontend/img/.DS_Store
  Frontend/img/product/.DS_Store
  Frontend/img/product/phones/.DS_Store
  Frontend/img/product/phones/Phone1.jpeg
  Frontend/img/product/phones/Phone10.jpeg
  Frontend/img/product/phones/Phone11.jpeg
  Frontend/img/product/phones/Phone12.jpeg
  Frontend/img/product/phones/Phone2.jpeg
  Frontend/img/product/phones/Phone3.jpeg
  Frontend/img/product/phones/Phone4.jpeg
  Frontend/img/product/phones/Phone5.jpeg
  Frontend/img/product/phones/Phone6.jpeg
  Frontend/img/product/phones/Phone7.jpeg
  Frontend/img/product/phones/Phone8.jpeg
  Frontend/img/product/phones/Phone9.jpeg
Labels: enhancement

#49 Fixed profile page fields
  project341/resources/views/profile/update-profile-information-form.blade.php
Labels: Task

#50 Redirect Login page and created layout
  .DS_Store
  project341/app/Http/Middleware/RedirectIfAuthenticated.php
  project341/app/Providers/RouteServiceProvider.php
  project341/resources/views/navigation-menu.blade.php
  project341/routes/web.php
Labels: Task

#51 Added logo to login/register page
  project341/resources/views/vendor/jetstream/components/application-mark.blade.php
  project341/resources/views/vendor/jetstream/components/authentication-card-logo.blade.php
Labels: Task
